BEGIN

  DECLARE v_start_date DATE;
  DECLARE v_end_date DATE;

  SET (v_start_date, v_end_date) = (
    SELECT AS STRUCT
      CASE WHEN dow IN (4, 5) THEN anchor_friday ELSE DATE_SUB(anchor_friday, INTERVAL 7 DAY) END AS DS_START_DATE,
      CASE WHEN dow IN (4, 5) THEN DATE_ADD(anchor_friday, INTERVAL 6 DAY) ELSE DATE_SUB(anchor_friday, INTERVAL 1 DAY) END AS DS_END_DATE
    FROM (
      SELECT current_dt, EXTRACT(DAYOFWEEK FROM current_dt) AS dow,
        DATE_SUB(current_dt, INTERVAL MOD(EXTRACT(DAYOFWEEK FROM current_dt) - 6 + 7, 7) DAY) AS anchor_friday
      FROM (SELECT CURRENT_DATE('America/Sao_Paulo') AS current_dt)
    )
  );

  DELETE FROM `shopper-datalakehouse-qa.Ranking_Performance.Ranking Semanal`
  WHERE data_inicio_periodo = v_start_date;

  INSERT INTO `shopper-datalakehouse-qa.Ranking_Performance.Ranking Semanal` (
    data_inicio_periodo, data_fim_periodo, data_processamento,
    MATRICULA, fc, setor_principal, turno, atribuicao,
    status_ranking, motivo_desqualificacao, pontuacao_final, pontuacao_potencial,
    posicao_ranking_fc, valor_bonificacao, EXPECTED_POINTS, EXPECTED_FACTOR,
    FALTAS, ATESTADOS, ADVERTENCIAS, ALOCACAO_INDEVIDA, atrasos, declaracao_horas,
    HORAS_TRABALHADAS, HORAS_ESPERADAS, PONTOS_POSITIVOS, PONTOS_NEGATIVOS, VALID_POINTS,
    ITENS_PACKING, ITENS_PICKING, ITENS_FRESH, PACKS_FRACIONADOS, ITENS_CHECKIN,
    AUDITORIA_CONFERENCIA_MERCEARIA, AUDITORIA_CONFERENCIA_FRESH,
    AUDITORIA_CONFERENCIA_MERCEARIA_EXPRESS, AUDITORIA_CONFERENCIA_FRESH_EXPRESS,
    VOLUMES_EXPEDIDOS, VOLUMES_SMD_EXPEDIDOS, PEDIDOS_MAPEADOS, ITENS_REBIPAGEM,
    ITENS_SAMEDAY, ITENS_SHOPPER_BR, ITENS_FALTANTES,
    CAIXARIAS_RECEBIMENTO_GAIOLA, CAIXARIAS_RECEBIMENTO_PALLET,
    CAIXARIAS_RECEBIMENTO_FRESH, CAIXARIAS_RECEBIMENTO_FLV,
    ERROS_PACKING, ERROS_PICKING, ERROS_FRESH, ERROS_REPORTADOS_CLIENTE,
    ERROS_ENCONTRADOS_REBIPAGEM, ERRO_REPOSICAO_PICKING_SECOS, ERRO_REPOSICAO_PK,
    ERRO_REPOSICAO_MERCEARIA, ERRO_REPOSICAO_FRESH, ERRO_REPOSICAO_TRANSFERENCIA,
    ERRO_RECEBIMENTO_FRESH, ERRO_RECEBIMENTO_MERCEARIA,
    ERRO_LOTE_FRESH, ERRO_LOTE_MERCEARIA, ERRO_FIFO,
    FALHA_REPOSICAO_MERCEARIA, FALHA_REPOSICAO_FRESH,
    DIVERGENCIA_RECEBIMENTO_FRESH, DIVERGENCIA_RECEBIMENTO_MERCEARIA,
    PEDIDO_SAMEDAY_NAO_MAPEADO_MERCEARIA, PEDIDO_SAMEDAY_NAO_MAPEADO_FRESH,
    TOTAL_ERROS_GERAL, TAXA_ERROS,
    ERROS_GESTAO_ESTOQUE,
    REPOSICAO_MERCEARIA_CHAO, REPOSICAO_MERCEARIA_ESCADA,
    REPOSICAO_MERCEARIA_EMPILHADEIRA, REPOSICAO_MERCEARIA_SALA_C,
    REPOSICAO_PICKING_SECOS, REPOSICAO_CHECKIN, REPOSICAO_TRANSFERENCIA,
    REPOSICAO_FRESH, REPOSICAO_PK, MAPEAMENTO_LOTE, REPOSICAO_TRANSFERENCIA_RECEBIDA,
    PERDAS_MERCEARIA, PERDAS_CONGELADOS_REFRIGERADOS, PERDAS_RETORNOS,
    DUPLICADO_PERDAS, LANCAMENTOS, PERDAS_FLV, PERDAS_PQV, PERDAS_INSUMOS,
    PERDAS_REMAPEAMENTO, PERDAS_VENCIDINHO_MERCEARIA, PERDAS_FLV_FRACIONAMENTO,
    LANCAMENTOS_VENCIDINHO_FRESH,
    PERDAS_RONDA_VALIDADE, PERDAS_RONDA_VALIDADE_FRESH, PERDAS_BB_CARNES,
    DIVERGENCIA_INVENTARIO, DIVERGENCIA_INVENTARIO_FRESH,
    ASSERTIVIDADE_ENDERECOS, ASSERTIVIDADE_ENDERECOS_FRESH,
    VALOR_A_RECEBER_ANTES_DO_KPI, saldo_da_carteira
  )

  WITH OrganogramaDedup AS (
    SELECT *, ROW_NUMBER() OVER(PARTITION BY MATRICULA ORDER BY DATA_ADM DESC) AS rn
    FROM `shopper-datalakehouse-qa.Ranking_Performance.Organograma`
    WHERE MATRICULA IS NOT NULL
  ),

  AuxFaltantes AS (
    SELECT DISTINCT SAFE_CAST(matricula AS INT64) AS MATRICULA
    FROM `shopper-datalakehouse-qa.Ranking_Performance.aux_faltantes`
    WHERE matricula IS NOT NULL
  ),

  BaseElegiveis AS (
    SELECT
      SAFE_CAST(o.MATRICULA AS INT64) AS MATRICULA,
      o.NOME,
      UPPER(TRIM(o.FC)) AS FC,
      UPPER(TRIM(o.SETOR)) AS setor_principal,
      UPPER(TRIM(o.TURNO)) AS turno,
      UPPER(TRIM(o.ATRIBUICAO)) AS atribuicao,
      UPPER(TRIM(o.FOLGA_FIXA)) AS FOLGA_FIXA
    FROM OrganogramaDedup o
    LEFT JOIN AuxFaltantes aux ON SAFE_CAST(o.MATRICULA AS INT64) = aux.MATRICULA
    WHERE o.rn = 1
      AND aux.MATRICULA IS NULL
      AND (
        (
          UPPER(TRIM(o.ATRIBUICAO)) IN (
            'PICKER/PACKER','INCLUIR FALTANTES','AUX. FALTANTES','CHECKOUT',
            'AUX. FRACIONAMENTO','SEPARAÇÃO','AUX. EXPEDIÇÃO','REBIPAGEM',
            'FISCAL','SUPERVISOR','FISCAL - PACKER','CONFERENTE'
          )
          AND UPPER(TRIM(o.SETOR)) IN (
            'PICKING','PACKING','EXPEDIÇÃO','FALTANTES',
            'OPERAÇÃO FRESH','FRACIONAMENTO','REBIPAGEM'
          )
        )
        OR UPPER(TRIM(o.SETOR)) IN (
          'REPOSIÇÃO','CHECK-IN','RECEBIMENTO','PRÉ EXPEDIÇÃO','CAMPINAS'
        )
        OR (
          UPPER(TRIM(o.SETOR)) = 'GESTÃO DE ESTOQUE'
          AND UPPER(TRIM(o.ATRIBUICAO)) IN (
            'INVENTÁRIO','INVENTÁRIO FRESH','PERDAS/DESFAZER PEDIDOS FRESH',
            'PERDAS MERCEARIA','FISCAL - PERDAS MERCEARIA',
            'FISCAL - PERDAS/DESFAZER PEDIDOS FRESH','FISCAL - PERDAS',
            'FISCAL - INVENTÁRIO','FISCAL PERDAS MERCEARIA',
            'FISCAL PERDAS/DESFAZER PEDIDOS FRESH','PERDAS FISCAL PERDAS',
            'FISCAL INVENTÁRIO'
          )
        )
      )
      AND UPPER(TRIM(o.ATRIBUICAO)) NOT IN (
        'RONDA/REPOSITOR FLV','IMPRESSÃO DE ROMANEIO','AUXILIAR NF','AUXILIAR NFE'
      )
      AND NOT (UPPER(TRIM(o.FC)) = 'FC2' AND UPPER(TRIM(o.ATRIBUICAO)) = 'INVENTÁRIO')
  ),

  DadosMedidas AS (
    SELECT SAFE_CAST(MATRICULA AS INT64) AS MATRICULA, COUNT(*) AS ADVERTENCIAS
    FROM `shopper-datalakehouse-qa.Ranking_Performance.Medidas Disciplinares `
    WHERE DATA_OCORRENCIA BETWEEN v_start_date AND v_end_date AND APLICADA IS TRUE AND INDEVIDA IS FALSE
    GROUP BY 1
  ),

  DadosAfastamentos AS (
    SELECT SAFE_CAST(Matricula AS INT64) AS MATRICULA, STRING_AGG(DISTINCT Motivo, ', ') AS motivo_afastamento
    FROM `shopper-datalakehouse-qa.Ranking_Performance.Afastamentos`
    WHERE Data_inicio <= v_end_date AND Data_final >= v_start_date
      AND UPPER(TRIM(Motivo)) IN ('AFASTAMENTO INSS','AFASTAMENTO NÃO REMUNERADO','LICENÇA MATERNIDADE','FÉRIAS')
    GROUP BY 1
  ),

  DadosCarteira AS (
    SELECT SAFE_CAST(matricula AS INT64) AS MATRICULA, CAST(saldo_pos_bonificacao AS STRING) AS SALDO
    FROM `shopper-datalakehouse-qa.Ranking_Performance.carteira_operação`
    WHERE data_inicio_ranking < v_start_date
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SAFE_CAST(matricula AS INT64) ORDER BY data_inicio_ranking DESC, update_at DESC, report_at DESC) = 1
  ),

  ErrosGestaoEstoque AS (
    SELECT registration_number AS MATRICULA, qtd_erros AS ERROS_GESTAO_ESTOQUE
    FROM `shopper-datalakehouse-qa.Ranking_Performance.curated_erros_gestao_estoque`
    WHERE reference_date = v_end_date
  ),

  MetricasProducao AS (
    SELECT
      SAFE_CAST(registration_number AS INT64) AS MATRICULA,
      SUM(CASE WHEN metric_type = 'PROMOTORA' THEN pontos_ponderados ELSE 0 END) AS pontos_positivos,
      SUM(CASE WHEN metric_type = 'DETRATORA' THEN pontos_ponderados ELSE 0 END) AS pontos_negativos,
      SUM(pontos_ponderados) AS valid_points,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ITENS CONFERIDOS EM MERCEARIA','ITENS CONFERIDOS MERCEARIA EXT','ITENS CONFERIDOS MERCEARIA EXPRESS','ITENS CONFERIDOS MERCEARIA SELECT') THEN qty ELSE 0 END) AS ITENS_PACKING,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ITENS PICKADOS EM MERCEARIA','ITENS PICKADOS MERCEARIA SELECT','ITENS PICKADOS MERCEARIA EXT') THEN qty ELSE 0 END) AS ITENS_PICKING,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ITENS PICKADOS EM FRESH','ITENS CONFERIDOS FRESH SMD','ITENS CONFERIDOS FRESH EXT','ITENS CONFERIDOS FRESH EXPRESS') THEN qty ELSE 0 END) AS ITENS_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PACKS FRACIONADOS' THEN qty ELSE 0 END) AS PACKS_FRACIONADOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ITENS CONFERIDOS NO CHECK-IN EM MERCEARIA','ITENS CONFERIDOS NO CHECK-IN EM FRESH','LISTA DE PEDIDOS CONFERIDOS NO CHECK-IN EM FRESH','LISTA DE PEDIDOS CONFERIDOS NO CHECK-IN EM MERCEARIA') THEN qty ELSE 0 END) AS ITENS_CHECKIN,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'AUDITORIA DE CONFERENCIA MERCEARIA' THEN qty ELSE 0 END) AS AUDITORIA_CONFERENCIA_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'AUDITORIA DE CONFERENCIA FRESH' THEN qty ELSE 0 END) AS AUDITORIA_CONFERENCIA_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'AUDITORIA DE CONFERENCIA MERCEARIA EXPRESS' THEN qty ELSE 0 END) AS AUDITORIA_CONFERENCIA_MERCEARIA_EXPRESS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'AUDITORIA DE CONFERENCIA FRESH EXPRESS' THEN qty ELSE 0 END) AS AUDITORIA_CONFERENCIA_FRESH_EXPRESS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'VOLUMES EXPEDIDOS' THEN qty ELSE 0 END) AS VOLUMES_EXPEDIDOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'VOLUMES SMD EXPEDIDOS' THEN qty ELSE 0 END) AS VOLUMES_SMD_EXPEDIDOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PEDIDOS MAPEADOS' THEN qty ELSE 0 END) AS PEDIDOS_MAPEADOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REBIPAGEM HOSPITAL' THEN qty ELSE 0 END) AS ITENS_REBIPAGEM,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ITENS CONFERIDOS EM MERCEARIA SMD' THEN qty ELSE 0 END) AS ITENS_SAMEDAY,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ITENS CONFERIDOS EM MERCEARIA BR' THEN qty ELSE 0 END) AS ITENS_SHOPPER_BR,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('FALTANTES','ITENS INCLUIDOS') THEN qty ELSE 0 END) AS ITENS_FALTANTES,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE '%CAIXARIAS RECEBIDAS EM MERCEARIA EM GAIOLA%' THEN qty ELSE 0 END) AS CAIXARIAS_RECEBIMENTO_GAIOLA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE '%CAIXARIAS RECEBIDAS EM FRESH%' THEN qty ELSE 0 END) AS CAIXARIAS_RECEBIMENTO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE '%CAIXARIAS FLV RECEBIDAS EM FRESH%' THEN qty ELSE 0 END) AS CAIXARIAS_RECEBIMENTO_FLV,
      SUM(CASE WHEN (UPPER(TRIM(metric_description)) LIKE '%CAIXARIAS RECEBIDAS%' OR UPPER(TRIM(metric_description)) LIKE '%RECEBIMENTO%') AND UPPER(TRIM(metric_description)) NOT LIKE '%GAIOLA%' AND UPPER(TRIM(metric_description)) NOT LIKE '%FRESH%' AND metric_type = 'PROMOTORA' THEN qty ELSE 0 END) AS CAIXARIAS_RECEBIMENTO_PALLET,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ITENS NÃO CONFERIDOS EM MERCEARIA' THEN qty ELSE 0 END) AS ERROS_PACKING,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ITENS NÃO PICKADOS EM MERCEARIA%' AND UPPER(TRIM(metric_description)) NOT LIKE '%ESTOQUE POSITIVO%' THEN qty ELSE 0 END) AS ERROS_PICKING,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ITENS NÃO PICKADOS EM FRESH%' THEN qty ELSE 0 END) AS ERROS_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO PARA O CLIENTE%' THEN qty ELSE 0 END) AS ERROS_REPORTADOS_CLIENTE,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ERRO ENCONTRADO NA REBIPAGEM' THEN qty ELSE 0 END) AS ERROS_ENCONTRADOS_REBIPAGEM,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ERRO REPOSIÇÃO PICKING SECOS' THEN qty ELSE 0 END) AS ERRO_REPOSICAO_PICKING_SECOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ERRO REPOSIÇÃO PK' THEN qty ELSE 0 END) AS ERRO_REPOSICAO_PK,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO REPOSIÇÃO MERCEARIA%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO MOVIMENTAÇÃO MERCEARIA%' THEN qty ELSE 0 END) AS ERRO_REPOSICAO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO REPOSIÇÃO FRESH%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO MOVIMENTAÇÃO FRESH%' THEN qty ELSE 0 END) AS ERRO_REPOSICAO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO REPOSIÇÃO TRANSFERÊNCIA%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO REPOSIÇÃO TRANFERÊNCIA%' THEN qty ELSE 0 END) AS ERRO_REPOSICAO_TRANSFERENCIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO CAIXARIAS RECEBIDAS FRESH%' THEN qty ELSE 0 END) AS ERRO_RECEBIMENTO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO CAIXARIAS RECEBIDAS MERCEARIA%' THEN qty ELSE 0 END) AS ERRO_RECEBIMENTO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ERRO MAPEAMENTO DE LOTE FRESH','ERRO MAPEMENTO DE LOTE FRESH') THEN qty ELSE 0 END) AS ERRO_LOTE_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('ERRO MAPEAMENTO DE LOTE MERCEARIA','ERRO MAPEMENTO DE LOTE MERCEARIA') THEN qty ELSE 0 END) AS ERRO_LOTE_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO DE FIFO%' THEN qty ELSE 0 END) AS ERRO_FIFO,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE '%LISTA PRIORIDADE%' OR UPPER(TRIM(metric_description)) LIKE '%PÁGINA PRIORIDADE%' THEN qty ELSE 0 END) AS FALHA_REPOSICAO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE '%LISTA FRESH%' OR UPPER(TRIM(metric_description)) LIKE '%PÁGINA FRESH%' THEN qty ELSE 0 END) AS FALHA_REPOSICAO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'DIVERGÊNCIA EM CAIXARIA RECEBIDA%' THEN qty ELSE 0 END) AS DIVERGENCIA_RECEBIMENTO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'DIVERGÊNCIA EM CAIXARIA RECEBIDA EM MERCEARIA' THEN qty ELSE 0 END) AS DIVERGENCIA_RECEBIMENTO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PEDIDO SAME-DAY NÃO MAPEADO EM MERCEARIA' THEN qty ELSE 0 END) AS PEDIDO_SAMEDAY_NAO_MAPEADO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PEDIDO SAME-DAY NÃO MAPEADO EM FRESH' THEN qty ELSE 0 END) AS PEDIDO_SAMEDAY_NAO_MAPEADO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'ERRO PARA O CLIENTE%' OR UPPER(TRIM(metric_description)) LIKE 'ITENS NÃO PICKADOS%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO REPOSIÇÃO%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO DE FIFO%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO DE MOVIMENTAÇÃO%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO DE ARMAZENAGEM%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO MOVIMENTAÇÃO%' OR UPPER(TRIM(metric_description)) LIKE '%LISTA PRIORIDADE%' OR UPPER(TRIM(metric_description)) LIKE '%PÁGINA PRIORIDADE%' OR UPPER(TRIM(metric_description)) LIKE '%LISTA FRESH%' OR UPPER(TRIM(metric_description)) LIKE 'ERRO CAIXARIAS RECEBIDAS%' OR UPPER(TRIM(metric_description)) IN ('ITENS NÃO CONFERIDOS EM MERCEARIA','ERRO ENCONTRADO NA REBIPAGEM') THEN qty ELSE 0 END) AS TOTAL_ERROS_GERAL,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO MERCEARIA: CHÃO' THEN qty ELSE 0 END) AS REPOSICAO_MERCEARIA_CHAO,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO MERCEARIA: ESCADA' THEN qty ELSE 0 END) AS REPOSICAO_MERCEARIA_ESCADA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO MERCEARIA: EMPILHADEIRA' THEN qty ELSE 0 END) AS REPOSICAO_MERCEARIA_EMPILHADEIRA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO MERCEARIA: SALA C' THEN qty ELSE 0 END) AS REPOSICAO_MERCEARIA_SALA_C,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO PICKING SECOS' THEN qty ELSE 0 END) AS REPOSICAO_PICKING_SECOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO CHECKIN' THEN qty ELSE 0 END) AS REPOSICAO_CHECKIN,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO TRANSFERÊNCIA' THEN qty ELSE 0 END) AS REPOSICAO_TRANSFERENCIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO FRESH' THEN qty ELSE 0 END) AS REPOSICAO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO PK' THEN qty ELSE 0 END) AS REPOSICAO_PK,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'MAPEAMENTO DE LOTE%' THEN qty ELSE 0 END) AS MAPEAMENTO_LOTE,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'REPOSIÇÃO TRANSFERÊNCIA RECEBIDA' THEN qty ELSE 0 END) AS REPOSICAO_TRANSFERENCIA_RECEBIDA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'PERDAS: MERCEARIA%' THEN qty ELSE 0 END) AS PERDAS_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'PERDAS: CONGELADOS E REFRIGERADOS%' THEN qty ELSE 0 END) AS PERDAS_CONGELADOS_REFRIGERADOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'PERDAS: RETORNOS%' THEN qty ELSE 0 END) AS PERDAS_RETORNOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'DUPLICADO: PERDAS%' OR UPPER(TRIM(metric_description)) LIKE 'DUPLICADO: LANÇAMENTO%' THEN qty ELSE 0 END) AS DUPLICADO_PERDAS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) LIKE 'LANÇAMENTO%' THEN qty ELSE 0 END) AS LANCAMENTOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: FLV' THEN qty ELSE 0 END) AS PERDAS_FLV,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: PQV' THEN qty ELSE 0 END) AS PERDAS_PQV,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: INSUMOS' THEN qty ELSE 0 END) AS PERDAS_INSUMOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: REMAPEAMENTO' THEN qty ELSE 0 END) AS PERDAS_REMAPEAMENTO,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('PERDAS: VENDICINHO MERCEARIA','PERDAS: VENCIDINHO MERCEARIA') THEN qty ELSE 0 END) AS PERDAS_VENCIDINHO_MERCEARIA,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: FLV - FRACIONAMENTO' THEN qty ELSE 0 END) AS PERDAS_FLV_FRACIONAMENTO,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) IN ('LANÇAMENTOS DE VENCIDINHO FRESH','LANÇAMENTO VENCIDINHO FRESH') THEN qty ELSE 0 END) AS LANCAMENTOS_VENCIDINHO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: RONDA DE VALIDADE'       THEN qty ELSE 0 END) AS PERDAS_RONDA_VALIDADE,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: RONDA DE VALIDADE FRESH' THEN qty ELSE 0 END) AS PERDAS_RONDA_VALIDADE_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'PERDAS: BB CARNES'               THEN qty ELSE 0 END) AS PERDAS_BB_CARNES,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ENDEREÇOS COM DIVERGÊNCIA DE INVENTÁRIO' THEN qty ELSE 0 END) AS DIVERGENCIA_INVENTARIO,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ENDEREÇOS COM DIVERGÊNCIA DE INVENTÁRIO FRESH' THEN qty ELSE 0 END) AS DIVERGENCIA_INVENTARIO_FRESH,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ASSERTIVIDADE DE ENDEREÇOS' THEN qty ELSE 0 END) AS ASSERTIVIDADE_ENDERECOS,
      SUM(CASE WHEN UPPER(TRIM(metric_description)) = 'ASSERTIVIDADE DE ENDEREÇOS FRESH' THEN qty ELSE 0 END) AS ASSERTIVIDADE_ENDERECOS_FRESH,
      SUM(CASE WHEN metric_type IN ('PROMOTORA','DETRATORA') THEN ABS(qty) ELSE 0 END) AS TOTAL_ITENS_GERAL
    FROM `shopper-datalakehouse-qa.Ranking_Performance.performance_extract_points_table`
    WHERE reference_date BETWEEN v_start_date AND v_end_date
    GROUP BY registration_number
  ),

  DadosPonto AS (
    SELECT
      SAFE_CAST(p.registration_number AS INT64) AS MATRICULA,
      SUM(IF(al.matricula IS NOT NULL, 0, p.expected_points)) AS EXPECTED_POINTS,
      MAX(IF(al.matricula IS NOT NULL, 1, 0)) AS flag_ajuda_lojinha,
      SUM(IF(p.worked_hours IS NOT NULL, EXTRACT(HOUR FROM p.worked_hours)*3600+EXTRACT(MINUTE FROM p.worked_hours)*60+EXTRACT(SECOND FROM p.worked_hours), 0)) AS segundos_trabalhados,
      SUM(IF(p.expected_hours IS NOT NULL, EXTRACT(HOUR FROM p.expected_hours)*3600+EXTRACT(MINUTE FROM p.expected_hours)*60+EXTRACT(SECOND FROM p.expected_hours), 0)) AS segundos_esperados,
      COUNTIF(p.absence IS NOT NULL) AS FALTAS,
      COUNTIF(p.medical_certificate IS NOT NULL) AS ATESTADOS,
      COUNTIF(p.vacation IS NOT NULL) AS ferias,
      COUNTIF(p.delay IS NOT NULL) AS qtd_delay,
      SUM(IF(p.delay IS NOT NULL, EXTRACT(HOUR FROM p.delay)*3600+EXTRACT(MINUTE FROM p.delay)*60+EXTRACT(SECOND FROM p.delay), 0)) AS total_segundos_delay,
      COUNTIF(p.hours_declaration IS NOT NULL) AS qtd_hours_declaration,
      SUM(IF(p.hours_declaration IS NOT NULL, EXTRACT(HOUR FROM p.hours_declaration)*3600+EXTRACT(MINUTE FROM p.hours_declaration)*60+EXTRACT(SECOND FROM p.hours_declaration), 0)) AS total_segundos_declaration
    FROM `shopper-datalakehouse-qa.Ranking_Performance.Expected Points Tratada` AS p
    LEFT JOIN `shopper-datalakehouse-qa.Ranking_Performance.ajuda_lojinha` al
      ON SAFE_CAST(p.registration_number AS INT64) = al.matricula AND p.reference_date = al.data
    WHERE p.reference_date BETWEEN v_start_date AND v_end_date
    GROUP BY MATRICULA
  ),

  Consolidado AS (
    SELECT
      b.MATRICULA, b.FC, b.setor_principal, b.turno, b.atribuicao,
      COALESCE(pt.EXPECTED_POINTS, 0) AS EXPECTED_POINTS,
      COALESCE(pt.flag_ajuda_lojinha, 0) AS flag_ajuda_lojinha,
      CASE WHEN b.setor_principal = 'CAMPINAS' AND COALESCE(pt.EXPECTED_POINTS, 0) = 0 THEN 1.0
           ELSE SAFE_DIVIDE(1000000, COALESCE(pt.EXPECTED_POINTS, 0)) END AS factor,
      COALESCE(pr.valid_points, 0) AS valid_points,
      COALESCE(pr.pontos_positivos, 0) AS PONTOS_POSITIVOS,
      COALESCE(pr.pontos_negativos, 0) AS PONTOS_NEGATIVOS,
      pr.* EXCEPT(MATRICULA, valid_points, pontos_positivos, pontos_negativos),
      COALESCE(pt.FALTAS, 0) AS FALTAS,
      COALESCE(pt.ATESTADOS, 0) AS ATESTADOS,
      COALESCE(md.ADVERTENCIAS, 0) AS ADVERTENCIAS,
      af.motivo_afastamento,
      0 AS ALOCACAO_INDEVIDA,
      pt.total_segundos_delay, pt.total_segundos_declaration,
      pt.qtd_delay, pt.qtd_hours_declaration,
      pt.segundos_trabalhados, pt.segundos_esperados,
      cart.SALDO AS saldo_da_carteira,
      COALESCE(eg.ERROS_GESTAO_ESTOQUE, 0) AS ERROS_GESTAO_ESTOQUE
    FROM BaseElegiveis b
    LEFT JOIN MetricasProducao pr ON b.MATRICULA = pr.MATRICULA
    LEFT JOIN DadosPonto pt ON b.MATRICULA = pt.MATRICULA
    LEFT JOIN DadosMedidas md ON b.MATRICULA = md.MATRICULA
    LEFT JOIN DadosAfastamentos af ON b.MATRICULA = af.MATRICULA
    LEFT JOIN DadosCarteira cart ON b.MATRICULA = cart.MATRICULA
    LEFT JOIN ErrosGestaoEstoque eg ON b.MATRICULA = eg.MATRICULA
  ),

  KPI_Calc AS (
    SELECT SAFE_CAST(MATRICULA AS STRING) AS MATRICULA,
      ANY_VALUE(COALESCE(MULT_MATRICULA,1.0)*COALESCE(MULT_TURNO,1.0)*COALESCE(MULT_SETOR,1.0)*COALESCE(MULT_ATRIBUICAO,1.0)*COALESCE(MULT_FC,1.0)) AS mult_total,
      ANY_VALUE(OBSERVACAO_KPI) AS kpi_obs
    FROM `shopper-datalakehouse-qa.Ranking_Performance.KPIs_OPERAÇÃO`
    WHERE data_inicio = v_start_date
    GROUP BY 1
  ),

  RankingFinal AS (
    SELECT c.*,
      COALESCE(kpi.mult_total, 1.0) AS mult_total, kpi.kpi_obs,
      SAFE_DIVIDE(TOTAL_ERROS_GERAL, TOTAL_ITENS_GERAL) AS TAXA_ERROS,
      (valid_points * LEAST(1.7, factor)) AS pontuacao_potencial,
      CASE WHEN motivo_afastamento IS NOT NULL THEN motivo_afastamento
           WHEN FALTAS > 0        THEN 'Falta'
           WHEN ADVERTENCIAS > 0  THEN 'Advertência'
           WHEN ATESTADOS > 0     THEN 'Atestado'
           WHEN EXPECTED_POINTS = 0 AND setor_principal != 'CAMPINAS' THEN 'Escala Zerada'
           ELSE NULL END AS motivo_desqualificacao,
      CASE
        WHEN (motivo_afastamento IS NOT NULL OR FALTAS > 0 OR ADVERTENCIAS > 0
              OR ATESTADOS > 0
              OR (EXPECTED_POINTS = 0 AND setor_principal != 'CAMPINAS')) THEN 0
        ELSE (valid_points * LEAST(1.5, factor))
      END AS pontuacao_final
    FROM Consolidado c
    LEFT JOIN KPI_Calc kpi ON CAST(c.MATRICULA AS STRING) = kpi.MATRICULA
  ),

  Posicionamento AS (
    SELECT rf.*,
      UPPER(CASE
        WHEN rf.atribuicao LIKE '%SUPERVISOR%' THEN 'LIDERANÇA'
        WHEN rf.atribuicao LIKE '%FISCAL%' AND rf.setor_principal NOT IN ('PACKING','OPERAÇÃO FRESH','OPERACAO FRESH') THEN 'LIDERANÇA'
        WHEN rf.pontuacao_final = 0 AND rf.motivo_desqualificacao IS NOT NULL THEN 'DESQUALIFICADO'
        WHEN rf.mult_total = 0 AND (rf.kpi_obs LIKE '%RUPTURA%' OR rf.kpi_obs LIKE '%ERRO REPORTADO POR CLIENTE%')
          THEN IF(rf.pontuacao_final >= 1000000,'BONIFICAÇÃO ZERADA POR ERRO CLIENTE/RUPTURA (IA RECEBER)','BONIFICAÇÃO ZERADA POR ERRO CLIENTE/RUPTURA (NÃO IA RECEBER)')
        WHEN rf.mult_total = 0 THEN 'KPI ZERADO'
        WHEN rf.pontuacao_final >= 1000000 THEN 'BONIFICADO'
        ELSE 'ELEGÍVEL'
      END) AS status_ranking,
      CASE
        WHEN rf.atribuicao LIKE '%SUPERVISOR%' THEN NULL
        WHEN rf.atribuicao LIKE '%FISCAL%' AND rf.setor_principal NOT IN ('PACKING','OPERAÇÃO FRESH','OPERACAO FRESH') THEN NULL
        WHEN rf.pontuacao_final > 0 THEN RANK() OVER (PARTITION BY rf.FC ORDER BY rf.pontuacao_final DESC NULLS LAST)
        ELSE NULL
      END AS posicao_ranking_fc
    FROM RankingFinal rf
  ),

  MetricasMaximas AS (
    SELECT FC, MAX(pontuacao_final) AS max_pts
    FROM Posicionamento
    WHERE pontuacao_final >= 1000000
      AND motivo_desqualificacao IS NULL
      AND status_ranking <> 'LIDERANÇA'
    GROUP BY 1
  ),

  CalculoFinal AS (
    SELECT p.*,
      CASE
        WHEN p.pontuacao_final >= 1000000
          AND p.motivo_desqualificacao IS NULL
          AND p.status_ranking <> 'LIDERANÇA'
        THEN IF(COALESCE(mx.max_pts,0) <= 1000000, cfg.valor_minimo,
          ROUND(cfg.valor_minimo + ((p.pontuacao_final-1000000)/(mx.max_pts-1000000))*(cfg.valor_maximo-cfg.valor_minimo),2))
        ELSE 0
      END AS VALOR_A_RECEBER_ANTES_DO_KPI
    FROM Posicionamento p
    LEFT JOIN MetricasMaximas mx ON p.FC = mx.FC
    CROSS JOIN (SELECT valor_minimo, valor_maximo FROM `shopper-datalakehouse-qa.Ranking_Performance.Config_Bonificacao_Ranking` LIMIT 1) cfg
  )

  SELECT
    v_start_date, v_end_date, CURRENT_TIMESTAMP(),
    p.MATRICULA, p.FC, p.setor_principal, p.turno, p.atribuicao,
    p.status_ranking, p.motivo_desqualificacao, p.pontuacao_final, p.pontuacao_potencial,
    COALESCE(p.posicao_ranking_fc, 0) AS posicao_ranking_fc,
    COALESCE(ROUND(p.VALOR_A_RECEBER_ANTES_DO_KPI * p.mult_total, 2), 0) AS valor_bonificacao,
    p.EXPECTED_POINTS, LEAST(1.7, p.factor) AS EXPECTED_FACTOR,
    p.FALTAS, p.ATESTADOS, p.ADVERTENCIAS, p.ALOCACAO_INDEVIDA,
    FORMAT('%d (%02d:%02d:%02d)', p.qtd_delay, DIV(p.total_segundos_delay,3600), DIV(MOD(p.total_segundos_delay,3600),60), MOD(p.total_segundos_delay,60)) AS atrasos,
    FORMAT('%d (%02d:%02d:%02d)', p.qtd_hours_declaration, DIV(p.total_segundos_declaration,3600), DIV(MOD(p.total_segundos_declaration,3600),60), MOD(p.total_segundos_declaration,60)) AS declaracao_horas,
    COALESCE(p.segundos_trabalhados, 0), COALESCE(p.segundos_esperados, 0),
    p.PONTOS_POSITIVOS, p.PONTOS_NEGATIVOS, p.valid_points,
    COALESCE(p.ITENS_PACKING, 0), COALESCE(p.ITENS_PICKING, 0), COALESCE(p.ITENS_FRESH, 0),
    COALESCE(p.PACKS_FRACIONADOS, 0), COALESCE(p.ITENS_CHECKIN, 0),
    CAST(COALESCE(p.AUDITORIA_CONFERENCIA_MERCEARIA, 0) AS INT64),
    CAST(COALESCE(p.AUDITORIA_CONFERENCIA_FRESH, 0) AS INT64),
    CAST(COALESCE(p.AUDITORIA_CONFERENCIA_MERCEARIA_EXPRESS, 0) AS INT64),
    CAST(COALESCE(p.AUDITORIA_CONFERENCIA_FRESH_EXPRESS, 0) AS INT64),
    COALESCE(p.VOLUMES_EXPEDIDOS, 0), COALESCE(p.VOLUMES_SMD_EXPEDIDOS, 0),
    COALESCE(p.PEDIDOS_MAPEADOS, 0), COALESCE(p.ITENS_REBIPAGEM, 0),
    COALESCE(p.ITENS_SAMEDAY, 0), COALESCE(p.ITENS_SHOPPER_BR, 0), COALESCE(p.ITENS_FALTANTES, 0),
    COALESCE(p.CAIXARIAS_RECEBIMENTO_GAIOLA, 0), COALESCE(p.CAIXARIAS_RECEBIMENTO_PALLET, 0),
    COALESCE(p.CAIXARIAS_RECEBIMENTO_FRESH, 0), COALESCE(p.CAIXARIAS_RECEBIMENTO_FLV, 0),
    COALESCE(p.ERROS_PACKING, 0), COALESCE(p.ERROS_PICKING, 0), COALESCE(p.ERROS_FRESH, 0),
    COALESCE(p.ERROS_REPORTADOS_CLIENTE, 0), COALESCE(p.ERROS_ENCONTRADOS_REBIPAGEM, 0),
    COALESCE(p.ERRO_REPOSICAO_PICKING_SECOS, 0), COALESCE(p.ERRO_REPOSICAO_PK, 0),
    COALESCE(p.ERRO_REPOSICAO_MERCEARIA, 0), COALESCE(p.ERRO_REPOSICAO_FRESH, 0),
    COALESCE(p.ERRO_REPOSICAO_TRANSFERENCIA, 0),
    COALESCE(p.ERRO_RECEBIMENTO_FRESH, 0), COALESCE(p.ERRO_RECEBIMENTO_MERCEARIA, 0),
    COALESCE(p.ERRO_LOTE_FRESH, 0), COALESCE(p.ERRO_LOTE_MERCEARIA, 0),
    COALESCE(p.ERRO_FIFO, 0),
    COALESCE(p.FALHA_REPOSICAO_MERCEARIA, 0), COALESCE(p.FALHA_REPOSICAO_FRESH, 0),
    COALESCE(p.DIVERGENCIA_RECEBIMENTO_FRESH, 0), COALESCE(p.DIVERGENCIA_RECEBIMENTO_MERCEARIA, 0),
    COALESCE(p.PEDIDO_SAMEDAY_NAO_MAPEADO_MERCEARIA, 0), COALESCE(p.PEDIDO_SAMEDAY_NAO_MAPEADO_FRESH, 0),
    COALESCE(p.TOTAL_ERROS_GERAL, 0), COALESCE(p.TAXA_ERROS, 0),
    p.ERROS_GESTAO_ESTOQUE,
    COALESCE(p.REPOSICAO_MERCEARIA_CHAO, 0), COALESCE(p.REPOSICAO_MERCEARIA_ESCADA, 0),
    COALESCE(p.REPOSICAO_MERCEARIA_EMPILHADEIRA, 0), COALESCE(p.REPOSICAO_MERCEARIA_SALA_C, 0),
    COALESCE(p.REPOSICAO_PICKING_SECOS, 0), COALESCE(p.REPOSICAO_CHECKIN, 0),
    COALESCE(p.REPOSICAO_TRANSFERENCIA, 0), COALESCE(p.REPOSICAO_FRESH, 0),
    COALESCE(p.REPOSICAO_PK, 0), COALESCE(p.MAPEAMENTO_LOTE, 0),
    COALESCE(p.REPOSICAO_TRANSFERENCIA_RECEBIDA, 0),
    COALESCE(p.PERDAS_MERCEARIA, 0), COALESCE(p.PERDAS_CONGELADOS_REFRIGERADOS, 0),
    COALESCE(p.PERDAS_RETORNOS, 0), COALESCE(p.DUPLICADO_PERDAS, 0),
    COALESCE(p.LANCAMENTOS, 0), COALESCE(p.PERDAS_FLV, 0), COALESCE(p.PERDAS_PQV, 0),
    COALESCE(p.PERDAS_INSUMOS, 0), COALESCE(p.PERDAS_REMAPEAMENTO, 0),
    COALESCE(p.PERDAS_VENCIDINHO_MERCEARIA, 0), COALESCE(p.PERDAS_FLV_FRACIONAMENTO, 0),
    COALESCE(p.LANCAMENTOS_VENCIDINHO_FRESH, 0),
    COALESCE(p.PERDAS_RONDA_VALIDADE, 0),
    COALESCE(p.PERDAS_RONDA_VALIDADE_FRESH, 0),
    COALESCE(p.PERDAS_BB_CARNES, 0),
    COALESCE(p.DIVERGENCIA_INVENTARIO, 0), COALESCE(p.DIVERGENCIA_INVENTARIO_FRESH, 0),
    COALESCE(p.ASSERTIVIDADE_ENDERECOS, 0), COALESCE(p.ASSERTIVIDADE_ENDERECOS_FRESH, 0),
    IF(p.VALOR_A_RECEBER_ANTES_DO_KPI <> ROUND(p.VALOR_A_RECEBER_ANTES_DO_KPI * p.mult_total, 2) AND p.VALOR_A_RECEBER_ANTES_DO_KPI > 0, p.VALOR_A_RECEBER_ANTES_DO_KPI, 0) AS VALOR_A_RECEBER_ANTES_DO_KPI,
    COALESCE(p.saldo_da_carteira, '0') AS saldo_da_carteira
  FROM CalculoFinal p
  QUALIFY ROW_NUMBER() OVER (PARTITION BY p.MATRICULA ORDER BY p.pontuacao_final DESC) = 1
  ORDER BY p.FC, p.posicao_ranking_fc ASC NULLS LAST;

END;
