CREATE OR REPLACE TABLE `shopper-datalakehouse-qa.Ranking_Performance.Tabela_Comparativo_Atividades` AS

WITH Base_View_Compat AS (
  SELECT
    SAFE_CAST(TRIM(CAST(MATRICULA AS STRING)) AS INT64) AS MATRICULA,
    CAST(ATIVIDADE AS STRING) AS ATIVIDADE,
    CAST(TIPO AS STRING) AS TIPO,
    CAST(CLASSIFICACAO_ERRO AS STRING) AS CLASSIFICACAO_ERRO,
    CAST(DATA_INICIO AS DATE) AS DATA_INICIO,
    CAST(DATA_FINAL AS DATE) AS DATA_FINAL,
    CAST(QTD AS INT64) AS QTD,
    CAST(TAXA_ERRO AS FLOAT64) AS TAXA_ERRO
  FROM `shopper-datalakehouse-qa.Ranking_Performance.View_Detalhe_Atividades_Semanal`
),

Historico_Com_Lag AS (
  SELECT
    MATRICULA,
    ATIVIDADE,
    TIPO,
    CLASSIFICACAO_ERRO,
    DATA_INICIO AS DATA_ATUAL,
    DATA_FINAL,
    QTD AS QTD_ATUAL,
    TAXA_ERRO AS TAXA_ATUAL,

    LAG(DATA_INICIO) OVER (
      PARTITION BY MATRICULA, ATIVIDADE, TIPO, CLASSIFICACAO_ERRO
      ORDER BY DATA_INICIO ASC
    ) AS DATA_ANTERIOR_REAL,

    LAG(QTD) OVER (
      PARTITION BY MATRICULA, ATIVIDADE, TIPO, CLASSIFICACAO_ERRO
      ORDER BY DATA_INICIO ASC
    ) AS QTD_ULTIMA_VEZ,

    LAG(TAXA_ERRO) OVER (
      PARTITION BY MATRICULA, ATIVIDADE, TIPO, CLASSIFICACAO_ERRO
      ORDER BY DATA_INICIO ASC
    ) AS TAXA_ULTIMA_VEZ

  FROM Base_View_Compat
),

Comparativo_Final AS (
  SELECT
    MATRICULA,
    ATIVIDADE,
    TIPO,
    CLASSIFICACAO_ERRO,
    DATA_ATUAL,
    DATA_FINAL,
    QTD_ATUAL,
    TAXA_ATUAL,

    CASE
      WHEN DATE_DIFF(DATA_ATUAL, DATA_ANTERIOR_REAL, DAY) = 7
        THEN QTD_ULTIMA_VEZ
      ELSE 0
    END AS QTD_ANTERIOR,

    CASE
      WHEN DATE_DIFF(DATA_ATUAL, DATA_ANTERIOR_REAL, DAY) = 7
        THEN TAXA_ULTIMA_VEZ
      ELSE 0
    END AS TAXA_ANTERIOR

  FROM Historico_Com_Lag
),

Organograma_Dedup AS (
  SELECT
    SAFE_CAST(TRIM(CAST(MATRICULA AS STRING)) AS INT64) AS MATRICULA,
    CRACHA,
    ROW_NUMBER() OVER (
      PARTITION BY SAFE_CAST(TRIM(CAST(MATRICULA AS STRING)) AS INT64)
      ORDER BY DATA_ADM DESC
    ) AS rn
  FROM `shopper-datalakehouse-qa.Ranking_Performance.Organograma`
  WHERE MATRICULA IS NOT NULL
)

SELECT
  c.MATRICULA,
  org.CRACHA,
  c.ATIVIDADE,
  c.TIPO,
  c.CLASSIFICACAO_ERRO,
  c.QTD_ATUAL,
  c.QTD_ANTERIOR,
  c.QTD_ATUAL - c.QTD_ANTERIOR AS EVOLUCAO_QTD,
  c.TAXA_ATUAL,
  c.TAXA_ANTERIOR,
  c.TAXA_ATUAL - c.TAXA_ANTERIOR AS EVOLUCAO_TAXA,
  c.DATA_ATUAL,
  c.DATA_FINAL

FROM Comparativo_Final c
LEFT JOIN Organograma_Dedup org
  ON c.MATRICULA = org.MATRICULA
 AND org.rn = 1;
