config {
  type: "table",
  schema: "Ranking_Performance",
  name: "expedicao_raw",
  description: "Expedição raw — Atividades por Romaneio da planilha Google Sheets.",
  bigquery: {
    externalDataConfiguration: {
      sourceFormat: "GOOGLE_SHEETS",
      sourceUris: ["https://docs.google.com/spreadsheets/d/1cJ73I0ySUaY_udx7bNpMGiN-xhxPuAOmwJDAOQVtGIc/edit"],
      googleSheetsOptions: { range: "Atividades por Romaneio!A2:E", skipLeadingRows: 1 },
      ignoreUnknownValues: true,
      schema: { fields: [
        { name: "matricula",  type: "INT64" },
        { name: "romaneio",   type: "STRING" },
        { name: "bipagem_1",  type: "TIMESTAMP" },
        { name: "bipagem_2",  type: "TIMESTAMP" },
        { name: "data",       type: "DATE" }
      ]}
    }
  }
}

SELECT * FROM ${self()}
